---

# Settings jitsi.videobridge
url_jitsi_hostname: localhost
url_jitsi_domain: quersys.com
USERNAME: jvb
PASSWORD: 123456789
MUC_JIDS: quersys.com
MUC_NICKNAME: jvbx
siguiente_shard: 1
# Settings jitsi.videobridge